-- Unity Catalog ABAC row-filter **policies** only (no ALTER TABLE … SET ROW FILTER).
-- Replace melissap.demo_dynamic_abac with your {catalog}.{schema}.
--
-- Governed tags (see bundle vars / seed_tables.py):
--   - ``abac_tag_key`` + ``abac_tag_value`` (default ``true``) on each *_with_abac table; empty value → key-only ``SET TAG ON TABLE``.
--   - ``abac_tag_key2`` + optional ``abac_tag_key2_value`` on ``patient_id``; empty → key-only column tag; policy uses ``has_tag`` or ``has_tag_value`` in ``MATCH COLUMNS``.
--
-- Principals: ``All account users`` then ``account users`` if the name differs by workspace.
--
-- See README for bundle variables and APPLY TAG / MANAGE requirements.
